import fs from "node:fs";
import path from "node:path";

import { parseDocument } from "yaml";
import { getAssignmentForEdit } from "./assignmentEditService.js";
import { escapeHtml } from "./htmlEscape.js";
import type { CourseSetupDiagnostic } from "./ipc.js";

export const STUDENT_ACCESS_PAGES_INDEX_PATH = "index.html";
export const STUDENT_ACCESS_PAGES_ROBOTS_PATH = "robots.txt";
export const STUDENT_ACCESS_PAGES_ROBOTS_META =
  '<meta name="robots" content="noindex, nofollow" />';

const TERM_CODE_PATTERN = /^\d{2}s[123]$/u;
const ASSIGNMENT_SLUG_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]*$/u;
const STUDENT_REPOSITORIES_FILE_NAME = "student-repositories.html";
const GENERATOR_NAME = "Graider student access pages";
const GENERATOR_META = `<meta name="generator" content="${GENERATOR_NAME}" />`;
const ROBOTS_MARKER = `# Generated by ${GENERATOR_NAME}`;
const ROBOTS_CONTENT = `${ROBOTS_MARKER}\nUser-agent: *\nDisallow: /\n`;

export interface StudentAccessPagesIndexCourse {
  readonly code: string | null;
  readonly title: string | null;
}

interface IndexTerm {
  readonly code: string;
  readonly displayName: string;
  readonly academicYear: number;
  readonly semester: number;
}

interface IndexEntry {
  readonly slug: string;
  readonly title: string;
  readonly href: string;
  readonly createdAt: number | null;
}

const diagnostic = (message: string): CourseSetupDiagnostic => ({ message });

const readYaml = (filePath: string): unknown => {
  try {
    return parseDocument(fs.readFileSync(filePath, "utf8")).toJS() as unknown;
  } catch {
    return null;
  }
};

const asRecord = (value: unknown): Record<string, unknown> | null =>
  typeof value === "object" && value !== null && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : null;

const listDirectories = (directory: string): readonly string[] => {
  try {
    return fs
      .readdirSync(directory, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
  } catch {
    return [];
  }
};

const readTerm = (courseFolderPath: string, termCode: string): IndexTerm | null => {
  const term = asRecord(
    asRecord(readYaml(path.join(courseFolderPath, "terms", termCode, "term.yml")))?.term
  );
  const academicYear = term?.academic_year;
  const semester = term?.semester;
  if (typeof academicYear !== "number" || typeof semester !== "number") return null;
  const displayName = term?.display_name;
  return {
    code: termCode,
    displayName:
      typeof displayName === "string" && displayName.trim() !== "" ? displayName : termCode,
    academicYear,
    semester
  };
};

const compareTermsNewestFirst = (left: IndexTerm, right: IndexTerm): number =>
  right.academicYear - left.academicYear || right.semester - left.semester;

const readMostRecentTerm = (courseFolderPath: string): IndexTerm | null =>
  listDirectories(path.join(courseFolderPath, "terms"))
    .filter((termCode) => TERM_CODE_PATTERN.test(termCode))
    .map((termCode) => readTerm(courseFolderPath, termCode))
    .filter((term): term is IndexTerm => term !== null)
    .sort(compareTermsNewestFirst)[0] ?? null;

const readEarliestRepositoryCreatedAt = (
  courseFolderPath: string,
  termCode: string,
  slug: string
): number | null => {
  const repositories = asRecord(
    readYaml(path.join(courseFolderPath, "terms", termCode, "manifests", slug, "manifest.yml"))
  )?.repositories;
  const createdAtTimes = (Array.isArray(repositories) ? repositories : [])
    .map((record) => asRecord(asRecord(record)?.repository)?.created_at)
    .map((value) => (typeof value === "string" ? Date.parse(value) : Number.NaN))
    .filter((time) => Number.isFinite(time));
  return createdAtTimes.length === 0 ? null : Math.min(...createdAtTimes);
};

const getStudentRepositoriesPath = (termCode: string, slug: string): string =>
  `terms/${termCode}/notifications/${slug}/${STUDENT_REPOSITORIES_FILE_NAME}`;

const readIndexEntries = (
  courseFolderPath: string,
  pagesRoot: string,
  term: IndexTerm
): readonly IndexEntry[] =>
  listDirectories(path.join(courseFolderPath, "terms", term.code, "assignments"))
    .filter((slug) => ASSIGNMENT_SLUG_PATTERN.test(slug))
    .filter((slug) =>
      fs.existsSync(path.join(pagesRoot, getStudentRepositoriesPath(term.code, slug)))
    )
    .map((slug) => {
      const assignment = getAssignmentForEdit(
        courseFolderPath,
        `terms/${term.code}/assignments/${slug}/assignment.yml`
      );
      const title = assignment.model?.assignmentTitle.trim() ?? "";
      return {
        slug,
        title: title === "" ? slug : title,
        href: getStudentRepositoriesPath(term.code, slug),
        createdAt: readEarliestRepositoryCreatedAt(courseFolderPath, term.code, slug)
      };
    });

// Most recently created first, using the earliest repository created_at in each
// assignment's manifest. Assumption (not specified): assignments without a
// created_at go last, ordered by title.
const compareEntriesNewestFirst = (left: IndexEntry, right: IndexEntry): number =>
  left.createdAt === right.createdAt
    ? left.title.localeCompare(right.title)
    : left.createdAt === null
      ? 1
      : right.createdAt === null
        ? -1
        : right.createdAt - left.createdAt;

const renderIndex = (
  course: StudentAccessPagesIndexCourse,
  term: IndexTerm,
  entries: readonly IndexEntry[]
): string => {
  const heading = [course.code, course.title, term.displayName, "Assignments"]
    .filter((value): value is string => value !== null && value.trim() !== "")
    .join(" ");
  const items = entries
    .map(
      (entry) =>
        `        <li><a class="assignment-link" href="${escapeHtml(entry.href)}">${escapeHtml(entry.title)}</a> (slug: ${escapeHtml(entry.slug)})</li>`
    )
    .join("\n");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    ${GENERATOR_META}
    ${STUDENT_ACCESS_PAGES_ROBOTS_META}
    <title>${escapeHtml(heading)}</title>
    <style>
      :root { color: #172033; background: #f6f8fc; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
      * { box-sizing: border-box; }
      body { margin: 0; min-width: 320px; }
      main { width: min(100% - 2rem, 48rem); margin: 0 auto; padding: 3rem 0; }
      h1 { margin: 0 0 1.5rem; font-size: clamp(1.75rem, 5vw, 2.25rem); letter-spacing: -0.025em; }
      .assignment-list { display: grid; gap: 1rem; margin: 0; padding-left: 1.5rem; line-height: 1.5; color: #526078; }
      .assignment-link { color: #2d6cdf; font-weight: 600; }
      .assignment-link:focus-visible { outline: 3px solid #2d6cdf; outline-offset: 3px; }
      @media (max-width: 480px) { main { width: min(100% - 1.5rem, 48rem); padding: 2rem 0; } }
    </style>
  </head>
  <body>
    <main>
      <h1>${escapeHtml(heading)}</h1>
      <ul class="assignment-list">
${items}
      </ul>
    </main>
  </body>
</html>
`;
};

const fileContains = (filePath: string, marker: string): boolean => {
  try {
    return fs.readFileSync(filePath, "utf8").includes(marker);
  } catch {
    return false;
  }
};

export const isGraiderStudentAccessPagesIndex = (pagesRoot: string): boolean =>
  fileContains(path.join(pagesRoot, STUDENT_ACCESS_PAGES_INDEX_PATH), GENERATOR_META);

const isGraiderStudentAccessPagesRobots = (pagesRoot: string): boolean =>
  fileContains(path.join(pagesRoot, STUDENT_ACCESS_PAGES_ROBOTS_PATH), ROBOTS_MARKER);

// Root files Graider wrote and may stage when publishing; hand-made files are excluded.
export const getGraiderStudentAccessPagesRootFiles = (pagesRoot: string): readonly string[] => [
  ...(isGraiderStudentAccessPagesIndex(pagesRoot) ? [STUDENT_ACCESS_PAGES_INDEX_PATH] : []),
  ...(isGraiderStudentAccessPagesRobots(pagesRoot) ? [STUDENT_ACCESS_PAGES_ROBOTS_PATH] : [])
];

const writeFileAtomically = (filePath: string, content: string, now: () => Date): void => {
  const temporaryPath = `${filePath}.${process.pid}.${now().getTime()}.tmp`;
  fs.writeFileSync(temporaryPath, content, "utf8");
  fs.renameSync(temporaryPath, filePath);
};

export const writeStudentAccessPagesRobots = (
  pagesRoot: string,
  now: () => Date
): readonly CourseSetupDiagnostic[] => {
  const robotsPath = path.join(pagesRoot, STUDENT_ACCESS_PAGES_ROBOTS_PATH);
  if (fs.existsSync(robotsPath) && !isGraiderStudentAccessPagesRobots(pagesRoot))
    return [
      diagnostic(
        "The Pages repository already has a robots.txt that Graider did not create, so it was not updated."
      )
    ];
  try {
    writeFileAtomically(robotsPath, ROBOTS_CONTENT, now);
    return [];
  } catch {
    return [diagnostic("Unable to write robots.txt for the student access pages.")];
  }
};

export const getStudentAccessPagesIndexLink = (pagePath: string): string =>
  path.posix.relative(path.posix.dirname(pagePath), STUDENT_ACCESS_PAGES_INDEX_PATH);

export const writeStudentAccessPagesIndex = (
  courseFolderPath: string,
  pagesRoot: string,
  course: StudentAccessPagesIndexCourse,
  now: () => Date
): readonly CourseSetupDiagnostic[] => {
  const indexPath = path.join(pagesRoot, STUDENT_ACCESS_PAGES_INDEX_PATH);
  if (fs.existsSync(indexPath) && !isGraiderStudentAccessPagesIndex(pagesRoot))
    return [
      diagnostic(
        "The Pages repository already has an index.html that Graider did not create, so the assignments page was not updated."
      )
    ];
  const term = readMostRecentTerm(courseFolderPath);
  if (term === null)
    return [diagnostic("Unable to determine the most recent term for the assignments page.")];
  try {
    const entries = [...readIndexEntries(courseFolderPath, pagesRoot, term)].sort(
      compareEntriesNewestFirst
    );
    writeFileAtomically(indexPath, renderIndex(course, term, entries), now);
    return [];
  } catch {
    return [diagnostic("Unable to write the assignments page.")];
  }
};
